---
title: "BID-Results-MCI-Report"
author: "Charalambos Themistocleous"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Clear Memory
rm(list = ls(all.names = TRUE))
#sink("vowel_stats_output_11_Aug_2018.txt")

set.seed(1000)
library("lme4")
library("lmerTest")
library("sjPlot")
library("xtable")
library("plyr")
library("ggplot2")
library("RColorBrewer")
library("gridExtra")
library("grid")
library("phonR")
# Printing
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
options(digits=2)
options(scipen=999)

# Definitions
.str <- function(x){
  # Modified str() to display all list elements within a level.
  # Charalambos Themistocleous 2015
  str(x, list.len=length(x))
}

# Get the trimmed mean predefined value at the 10%
mean1 <- function(x,...){
  mean(x,trim=.1)
}

# Open Data ----------------------------------------------------
a <- read.csv("BID_final.csv")
str(a)

d <- a[!a$condition=="SCI",]
d <- d[!d$File == "LABM-75GG-5KH4",] 
d <- d[!d$File == "79CJ-M7A3-FALX",] 
d <- d[!d$File == "TXLH-R239-CPQG",]

d <- droplevels(d)

# H1 H2 ---------------------------------------------------------------
h1h2p1 = ggplot(d, aes(x = condition, y = h1.h2, fill = gender)) + 
  # stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("H1-H2") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = quantile(d$h1.h2, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "H1-H2"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
h1h2p1

hist(d$h1.h2)

h1h2m <- lm(h1.h2 ~ condition*gender, data = d)
summary(h1h2m)
h1h2p2 = plot_model(h1h2m, type = "pred",  terms = c("condition")) + 
  ggtitle("H1-H2") + 
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Predicted H1-H2 values"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank())
h1h2p2 


#  Formant-Adjusted H1-H2  ---------------------------------------------------------------
formh1h2p1 = ggplot(d, aes(x = condition, y = h1.h2, fill = gender)) + 
  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Formant-Adjusted H1-H2") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = quantile(d$h1h2, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Formant-Adjusted H1-H2"
  ) +   theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
formh1h2p1



Bh1h2m <- lm(h1.h2~condition*gender, data = d)
summary(Bh1h2m)
plot_model(h1h2m, type = "pred",  terms = c("condition"))


# H1.A1  ---------------------------------------------------------------
H1A1plot = ggplot(d, aes(x = condition, y = H1.A1, fill = gender)) + 
  #stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("H1-A1") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = quantile(d$h1.h2, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "H1-A1"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
H1A1plot

H1.A1m <- lm(H1.A1~condition*gender, data = d)
summary(H1.A1m)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(H1.A1m, type = "pred",  terms = c("condition","gender"))


# H1.A3  ---------------------------------------------------------------
H1A3plot = ggplot(d, aes(x = condition, y = H1.A3, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("H1-A3") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #scale_y_continuous(limits = quantile(d$h1.h2, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "H1-A3"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

H1A3plot

boxplot(H1.A3~condition*gender, data=d)


H1.A3m <- lm(H1.A3~condition*gender, data = d, na.action=na.exclude)
summary(H1.A3m)
plot_model(H1.A3m, type = "pred",  terms = c("condition", "gender"))+ggtitle("H1-A3")+  theme_minimal()

library(apaTables)
apa.reg.table(H1.A3m, filename = "Table3_APA.doc", table.number = 2)


grid.arrange(h1h2p1, H1A1plot,H1A3plot,nrow=1, ncol=3)

# Putting plots together -----------------------------------------------


# Cepstral Peak Prominence   ---------------------------------------------------------------
# SIGNIFICANT

cpp_plot = ggplot(d, aes(x = condition, y = cpp, fill = gender)) + 
  #stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Cepstral Peak Prominence ") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = quantile(d$cpp, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Cepstral Peak Prominence"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

cpp_plot

cppm <- lmer(cpp~condition*gender+(1|speaker) , data = d)
cppm1 <- lm(cpp~condition*gender, data = d)
AIC(cppm,cppm1)
summary(cppm)
summary(cppm1)
library(sjmisc)
theme_set(theme_sjplot())
cpp_plot_pred = plot_model(cppm, type = "pred",  terms = c("condition"))
grid.arrange(cpp_plot, cpp_plot_pred,nrow = 1)
apa.reg.table(cppm1, filename = "Table4_APA.doc", table.number = 4)


# center_of_gravity  ---------------------------------------------------------------
cogplot= ggplot(d, aes(x = condition, y = center_of_gravity, fill = gender)) + 
  #stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Center of Gravity") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = quantile(d$center_of_gravity, c(0.1, 0.9))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Center of Gravity"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
cogplot

center_of_gravitym <- lmer( center_of_gravity~condition*gender+(1|speaker) , data = d)
center_of_gravitym1 <- lm( center_of_gravity~condition*gender, data = d)
summary(center_of_gravitym)
summary(center_of_gravitym1)
AIC(center_of_gravitym,center_of_gravitym1)

library(sjmisc)
theme_set(theme_sjplot())
plot_model(center_of_gravitym, type = "pred",  terms = c("condition"))


# Hammarberg_index  ---------------------------------------------------------------
hiplot = ggplot(d, aes(x = condition, y = Hammarberg_index, fill = gender)) + 
  #stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Hammarberg Index") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #scale_y_continuous(limits = quantile(d$Hammarberg_index, c(0, 0.01))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Hammarberg Index"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
hiplot



Hammarberg_indexm <- lmer(Hammarberg_index~condition*gender+(1|speaker) , data = d)
Hammarberg_indexm1 <- lm(Hammarberg_index~condition, data = d)
AIC(Hammarberg_indexm, Hammarberg_indexm1)
summary(Hammarberg_indexm)
summary(Hammarberg_indexm1)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(Hammarberg_indexm, type = "pred",  terms = c("condition"))


# Energy_Profile__250Hz  ---------------------------------------------------------------
e250plot=ggplot(d, aes(x = condition, y = Energy_Profile__250Hz, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Energy below 250Hz") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #scale_y_continuous(limits = (c(0, 1))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Energy below 250Hz"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
e250plot

Energy_Profile__250Hzm <- lmer(Energy_Profile__250Hz~condition*gender+(1|speaker) , data = d)
summary(Energy_Profile__250Hzm)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(Energy_Profile__250Hzm, type = "pred",  terms = c("condition"))

# Energy_below_500Hz  ---------------------------------------------------------------
e500plot=ggplot(d, aes(x = condition, y = energy_below_500Hz, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Energy below 500Hz") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = (c(0, 1))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Energy below 500Hz"
  ) +  theme_minimal() +
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
e500plot


energy_below_500Hzm <- lmer(energy_below_500Hz~condition*gender+(1|speaker) , data = d)
energy_below_500Hzm1 <- lm(energy_below_500Hz~condition*gender, data = d)
summary(energy_below_500Hzm)
summary(energy_below_500Hzm1)
AIC(energy_below_500Hzm,energy_below_500Hzm1)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(energy_below_500Hzm, type = "pred",  terms = c("condition"))


# Energy_below_1000Hz  ---------------------------------------------------------------
e1000plot=ggplot(d, aes(x = condition, y = energy_below_1000Hz, fill = gender)) + 
  #stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Energy below 1000Hz") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #scale_y_continuous(limits = quantile(d$energy_below_1000Hz, c(0, 1))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Energy below 1000Hz"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
e1000plot


energy_below_1000Hzm <- lmer(energy_below_1000Hz~condition*gender+(1|speaker) , data = d)
energy_below_1000Hzm1 <- lm(energy_below_1000Hz~condition*gender, data = d)
summary(energy_below_1000Hzm)
summary(energy_below_1000Hzm1)
AIC(energy_below_1000Hzm,energy_below_1000Hzm1)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(energy_below_1000Hzm, type = "pred",  terms = c("condition"))


# F_dispersion1_3  ---------------------------------------------------------------
ggplot(d, aes(x = condition, y = F_dispersion1_3, fill = gender)) + 
  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Average Distance from F1 to F3") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #  scale_y_continuous(limits = quantile(d$h1.h2, c(0, 1))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Average Distance from F1 to F3"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 




F_dispersion1_3m <- lmer(F_dispersion1_3~condition+(1|speaker) , data = d)
summary(F_dispersion1_3m)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(F_dispersion1_3m, type = "pred",  terms = c("condition"))



# F_dispersion1_5  ---------------------------------------------------------------
ggplot(d, aes(x = condition, y = F_dispersion1_5, fill = gender)) + 
  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Average Distance from F1 to F5") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #  scale_y_continuous(limits = quantile(d$h1.h2, c(0, 1))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Average Distance from F1 to F5"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

F_dispersion1_5m <- lmer(F_dispersion1_5~condition+(1|speaker) , data = d)
summary(F_dispersion1_5m)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(F_dispersion1_5m, type = "pred",  terms = c("condition"))


grid.arrange(h1h2p1, H1A1plot, H1A3plot, formh1h2p1, cpp_plot, cogplot, hiplot, e500plot, e1000plot, nrow = 3, ncol=4)


grid.arrange(cpp_plot, cogplot, hiplot, e250plot, e500plot, e1000plot, nrow = 2, ncol=3)


# median_pitch  ---------------------------------------------------------------
median_pitchp1 = ggplot(d, aes(x = condition, y = median_pitch, fill = gender)) + 
  # stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Median Pitch") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #scale_y_continuous(limits = c(0, 400)) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Median Pitch"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
median_pitchp1


median_pitchm <- lmer(median_pitch~condition*gender+(1|speaker), data = d)
summary(median_pitchm)
median_pitchp2 = plot_model(median_pitchm, type = "pred",  terms = c("condition")) +
  ggtitle("Predicted Median Pitch") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_y_continuous(limits = c(0, 400)) +
  scale_fill_brewer(palette = "Blues") +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Predicted Median Pitch"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
median_pitchp2

grid.arrange(median_pitchp1, median_pitchp2, nrow = 1)

# Jitter  ---------------------------------------------------------------

jitterplot = ggplot(d, aes(x = condition, y = jitter, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Jitter") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = c(0,0.10)) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Jitter"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
jitterplot

jitterm <- lmer(jitter~condition*gender+(1|speaker) , data = d) # interaction not possible 
summary(jitterm)
jitterm1 <- lm(jitter~condition*gender, data = d)
summary(jitterm1)

library(sjmisc)
theme_set(theme_sjplot())
plot_model(jitterm, type = "pred",  terms = c("condition"))


# Shimmer  ---------------------------------------------------------------
shimmerplot = ggplot(d, aes(x = condition, y = shimmer, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Shimmer") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(limits = c(0, 0.3)) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Shimmer"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
shimmerplot

shimmerm <- lmer(shimmer~condition*gender+(1|speaker) , data = d)
summary(shimmerm)

shimmerm1 <- lm(shimmer~condition*gender, data = d)
summary(shimmerm1)



library(sjmisc)
theme_set(theme_sjplot())
plot_model(shimmerm, type = "pred",  terms = c("condition"))



# Harmonicity  ---------------------------------------------------------------
harmonicityplot = ggplot(d, aes(x = condition, y = harmonicity, fill = gender)) + 
  #  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA) +
  ggtitle("Harmonicity") +
  scale_x_discrete(name = "PPA conditions")  + 
  scale_fill_brewer(palette = "Blues") +
  #  scale_y_continuous(limits = quantile(d$h1.h2, c(0, 0.3))) +
  labs(
    fill = "condition",
    x = "PPA conditions",
    y = "Harmonicity"
  ) + 
  theme(legend.position="top", legend.title = element_blank(), text = element_text(size=20), plot.title = element_text(hjust = 0.5),panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
harmonicityplot 


harmonicitym <- lmer(harmonicity~condition*gender+(1|speaker) , data = d)
summary(harmonicitym)

harmonicitym1 <- lmer(harmonicity~condition*gender+(1|speaker) , data = d)
summary(harmonicitym1)

library(sjmisc)
theme_set(theme_sjplot())
plot_model(harmonicitym, type = "pred",  terms = c("condition"))

grid.arrange(jitterplot, shimmerplot, harmonicityplot, ncol=3, nrow=1)

# Energy_Profile__250Hz  ---------------------------------------------------------------
e250plot = ggplot(d, aes(x = condition, y = Energy_Profile__250Hz, fill = gender)) + 
  scale_fill_brewer(palette = "Blues") + 
  # stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA)
e250plot

Energy_Profile__250Hzm <- lmer(Energy_Profile__250Hz~condition*gender+(1|speaker) , data = d)
summary(Energy_Profile__250Hzm)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(Energy_Profile__250Hzm, type = "pred",  terms = c("condition"))


# Energy_below_1000Hz  ---------------------------------------------------------------
eb1000 = ggplot(d, aes(x = condition, y = energy_below_1000Hz, fill = condition)) + 
  scale_fill_brewer(palette = "Blues") + 
  stat_summary(fun.y = mean, geom = "point") +
  geom_boxplot( outlier.shape = NA)
eb1000

grid.arrange(cpp_plot, cogplot, hiplot, e250plot, e500plot, e1000plot, eb1000, nrow = 4)

energy_below_1000Hzm <- lmer(energy_below_1000Hz~condition+(1|speaker) , data = d)
summary(energy_below_1000Hzm)
library(sjmisc)
theme_set(theme_sjplot())
plot_model(energy_below_1000Hzm, type = "pred",  terms = c("condition"))

